apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    component: grafana-deployment
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
