apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  template:
    spec:
      containers:
        - name: db
          volumeMounts:
            - name: config-volume
              mountPath: /var/lib/postgresql/config/
      volumes:
        - name: config-volume
          configMap:
            name: db-config