apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    component: auth
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
